# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Build Index File for a BGZF Reference Panel
#'
#' Reads a BGZF-compressed reference panel genotype file and writes an index
#' recording the byte offset (\code{fpos}) and line length for each SNP.
#' The resulting index file is required by most other functions in this package.
#'
#' @param reference_data_file Character. Path to the BGZF-compressed reference
#'   genotype file (e.g. \code{"/33KG/33kg_geno.gz"}).
#' @param output_file Character. Path for the output index file.
#'
#' @return Invisibly returns \code{NULL}. Writes the index to \code{output_file}.
#'   Each line contains: \code{fpos line_length}.
#'
#' @examples
#' \dontrun{
#' indexer(
#'   reference_data_file = "/33KG/33kg_geno.gz",
#'   output_file = "33kg_index.txt"
#' )
#' }
#' @export
indexer <- function(reference_data_file, output_file) {
    invisible(.Call(`_refPanelTools_indexer`, reference_data_file, output_file))
}

#' Compute Overall Reference Allele Frequency (AF1) per SNP
#'
#' Reads the BGZF-compressed reference genotype file and computes the
#' alternate allele frequency (AF1) across all populations combined.
#' AF1 is rounded up to 5 decimal places.
#'
#' @param reference_data_file Character. Path to the BGZF-compressed reference
#'   genotype file.
#' @param num_pops Integer. Total number of populations in the reference panel
#'   (e.g. \code{29} for 33KG).
#' @param output_file Character. Path for the output file. Each line contains
#'   the AF1 value for the corresponding SNP.
#'
#' @return Invisibly returns \code{NULL}. Writes one AF1 value per line to
#'   \code{output_file}.
#'
#' @examples
#' \dontrun{
#' cal_af1ref(
#'   reference_data_file = "/33KG/33kg_geno.gz",
#'   num_pops = 29,
#'   output_file = "33kg_af1ref.txt"
#' )
#' }
#' @export
cal_af1ref <- function(reference_data_file, num_pops, output_file) {
    invisible(.Call(`_refPanelTools_cal_af1ref`, reference_data_file, num_pops, output_file))
}

#' Extract Genotype Data for a Single Chromosome
#'
#' Extracts all SNP genotype records for a specified chromosome from the
#' BGZF-compressed reference panel, using the index file to seek efficiently.
#'
#' @param chr_num Integer. Chromosome number (1--22).
#' @param num_pops Integer. Total number of populations in the reference panel.
#' @param index_data_file Character. Path to the reference panel index file
#'   (output of \code{\link{indexer}}).
#' @param reference_data_file Character. Path to the BGZF-compressed reference
#'   genotype file.
#' @param ref_out_file Character. Output file path. Each line is a raw genotype
#'   record for one SNP.
#'
#' @return Invisibly returns \code{NULL}. Writes genotype records to
#'   \code{ref_out_file}.
#'
#' @examples
#' \dontrun{
#' extract_chr_data(
#'   chr_num = 22,
#'   num_pops = 29,
#'   index_data_file = "/33KG/33kg_index.gz",
#'   reference_data_file = "/33KG/33kg_geno.gz",
#'   ref_out_file = "33kg_chr22_geno.txt"
#' )
#' }
#' @export
extract_chr_data <- function(chr_num, num_pops, index_data_file, reference_data_file, ref_out_file) {
    invisible(.Call(`_refPanelTools_extract_chr_data`, chr_num, num_pops, index_data_file, reference_data_file, ref_out_file))
}

#' Extract Genotype Data for Specific Populations on One Chromosome
#'
#' Extracts SNP genotype data for a user-specified subset of populations
#' on a single chromosome. Population names are matched case-insensitively
#' against the reference population description file.
#'
#' @param chr_num Integer. Chromosome number (1--22).
#' @param pop_vec Character vector. Population abbreviations to include
#'   (e.g. \code{c("CEU", "YRI")}). Case-insensitive.
#' @param index_data_file Character. Path to the reference panel index file.
#' @param reference_data_file Character. Path to the BGZF-compressed reference
#'   genotype file.
#' @param reference_pop_desc_file Character. Path to the population description
#'   file (columns: \code{pop_abb num_subj sup_pop_abb}, with a header row).
#' @param ref_out_file Character. Output file path. Each line contains genotype
#'   strings and AF1 values for the selected populations only.
#'
#' @return Invisibly returns \code{NULL}. Writes filtered genotype records to
#'   \code{ref_out_file}.
#'
#' @examples
#' \dontrun{
#' extract_chr_pop_data(
#'   chr_num = 22,
#'   pop_vec = c("CEU", "YRI"),
#'   index_data_file = "/33KG/33kg_index.gz",
#'   reference_data_file = "/33KG/33kg_geno.gz",
#'   reference_pop_desc_file = "/33KG/33kg_pop_desc.txt",
#'   ref_out_file = "33kg_chr22_CEU_YRI_geno.txt"
#' )
#' }
#' @export
extract_chr_pop_data <- function(chr_num, pop_vec, index_data_file, reference_data_file, reference_pop_desc_file, ref_out_file) {
    invisible(.Call(`_refPanelTools_extract_chr_pop_data`, chr_num, pop_vec, index_data_file, reference_data_file, reference_pop_desc_file, ref_out_file))
}

#' Extract Population-Level AF1 for All SNPs on One Chromosome
#'
#' For each SNP on the specified chromosome, reads the per-population allele
#' frequency (AF1) fields from the reference genotype file and writes them
#' to the output — one line per SNP, space-separated AF1 values in the order
#' populations appear in the population description file.
#'
#' @param chr_num Integer. Chromosome number (1--22).
#' @param index_data_file Character. Path to the reference panel index file.
#' @param reference_data_file Character. Path to the BGZF-compressed reference
#'   genotype file.
#' @param reference_pop_desc_file Character. Path to the population description
#'   file (columns: \code{pop_abb num_subj sup_pop_abb}, with a header row).
#' @param ref_out_file Character. Output file path. Each line contains
#'   space-separated AF1 values for all populations for one SNP.
#'
#' @return Invisibly returns \code{NULL}. Writes AF1 matrix rows to
#'   \code{ref_out_file}.
#'
#' @examples
#' \dontrun{
#' extract_all_af1(
#'   chr_num = 22,
#'   index_data_file = "/33KG/33kg_index.gz",
#'   reference_data_file = "/33KG/33kg_geno.gz",
#'   reference_pop_desc_file = "/33KG/33kg_pop_desc.txt",
#'   ref_out_file = "33kg_chr22_af1.txt"
#' )
#' }
#' @export
extract_all_af1 <- function(chr_num, index_data_file, reference_data_file, reference_pop_desc_file, ref_out_file) {
    invisible(.Call(`_refPanelTools_extract_all_af1`, chr_num, index_data_file, reference_data_file, reference_pop_desc_file, ref_out_file))
}

#' Simulate AF1 and Association Z-scores Across All Chromosomes
#'
#' For each SNP across all chromosomes, draws a bootstrap sample of subjects
#' from specified populations (sampling with replacement), simulates a null
#' phenotype (standard normal), and computes the OLS association Z-score.
#' Use this to generate genome-wide null Z-score distributions.
#'
#' @param pop_vec Character vector. Population abbreviations to sample from
#'   (e.g. `c("CEU", "YRI")`). Case-insensitive. Each population may appear
#'   at most once.
#' @param num_sim_vec Integer vector. Number of subjects to sample from each
#'   population, where `num_sim_vec[i]` is the sample size for `pop_vec[i]`.
#'   Must be the same length as `pop_vec` and contain positive values. The
#'   pairing is positional, so `pop_vec` may be given in any order; it need
#'   not follow the order of the population description file.
#' @param index_data_file Character. Path to the reference panel index file.
#' @param reference_data_file Character. Path to the BGZF-compressed reference
#'   genotype file.
#' @param reference_pop_desc_file Character. Path to the population description
#'   file.
#' @param ref_out_file Character. Output file path. Space-separated columns:
#'   `rsid chr bp a1 a2 sim_af1 sim_z`.
#'
#' @return Invisibly returns `NULL`. Writes simulation results to
#'   `ref_out_file`.
#'
#' @seealso [simulate_af1_z()] for single-chromosome simulation.
#'
#' @examples
#' \dontrun{
#' simulate_af1_z_allchr(
#'   pop_vec = c("CEU", "YRI"),
#'   num_sim_vec = c(100, 100),
#'   index_data_file = "/33KG/33kg_index.gz",
#'   reference_data_file = "/33KG/33kg_geno.gz",
#'   reference_pop_desc_file = "/33KG/33kg_pop_desc.txt",
#'   ref_out_file = "sim_allchr_results.txt"
#' )
#' }
#' @export
simulate_af1_z_allchr <- function(pop_vec, num_sim_vec, index_data_file, reference_data_file, reference_pop_desc_file, ref_out_file) {
    invisible(.Call(`_refPanelTools_simulate_af1_z_allchr`, pop_vec, num_sim_vec, index_data_file, reference_data_file, reference_pop_desc_file, ref_out_file))
}

#' Simulate AF1 and Association Z-scores for One Chromosome
#'
#' Same simulation procedure as [simulate_af1_z_allchr()] but restricted to a
#' single chromosome. Bootstrap subject indices are drawn once and reused
#' across all SNPs on that chromosome (consistent sampling).
#'
#' @param chr_num Integer. Chromosome number (1--22).
#' @param pop_vec Character vector. Population abbreviations to sample from.
#'   Case-insensitive. Each population may appear at most once.
#' @param num_sim_vec Integer vector. Number of subjects to sample per
#'   population, where `num_sim_vec[i]` is the sample size for `pop_vec[i]`.
#'   Must be the same length as `pop_vec` and contain positive values. The
#'   pairing is positional, so `pop_vec` may be given in any order; it need
#'   not follow the order of the population description file.
#' @param index_data_file Character. Path to the reference panel index file.
#' @param reference_data_file Character. Path to the BGZF-compressed reference
#'   genotype file.
#' @param reference_pop_desc_file Character. Path to the population description
#'   file.
#' @param ref_out_file Character. Output file path. Space-separated columns:
#'   `rsid chr bp a1 a2 sim_af1 sim_z`.
#'
#' @return Invisibly returns `NULL`. Writes simulation results to
#'   `ref_out_file`.
#'
#' @seealso [simulate_af1_z_allchr()] for genome-wide simulation.
#'
#' @examples
#' \dontrun{
#' simulate_af1_z(
#'   chr_num = 22,
#'   pop_vec = c("CEU", "YRI"),
#'   num_sim_vec = c(100, 100),
#'   index_data_file = "/33KG/33kg_index.gz",
#'   reference_data_file = "/33KG/33kg_geno.gz",
#'   reference_pop_desc_file = "/33KG/33kg_pop_desc.txt",
#'   ref_out_file = "sim_chr22_results.txt"
#' )
#' }
#' @export
simulate_af1_z <- function(chr_num, pop_vec, num_sim_vec, index_data_file, reference_data_file, reference_pop_desc_file, ref_out_file) {
    invisible(.Call(`_refPanelTools_simulate_af1_z`, chr_num, pop_vec, num_sim_vec, index_data_file, reference_data_file, reference_pop_desc_file, ref_out_file))
}

#' Extract Genotype Data for a Genomic Region
#'
#' Extracts all SNP genotype records within a specified base-pair range
#' on a chromosome. Uses the index file for efficient random access into
#' the BGZF-compressed reference panel.
#'
#' @param chr_num Integer. Chromosome number (1--22).
#' @param start_bp Integer. Start base pair position (inclusive).
#' @param end_bp Integer. End base pair position (inclusive).
#' @param num_pops Integer. Total number of populations in the reference panel.
#' @param index_data_file Character. Path to the reference panel index file.
#' @param reference_data_file Character. Path to the BGZF-compressed reference
#'   genotype file.
#' @param ref_out_file Character. Output file path. Each line is a raw genotype
#'   record for one SNP in the region.
#'
#' @return Invisibly returns \code{NULL}. Writes genotype records to
#'   \code{ref_out_file}.
#'
#' @examples
#' \dontrun{
#' extract_reg_data(
#'   chr_num = 14,
#'   start_bp = 104000000,
#'   end_bp = 104200000,
#'   num_pops = 29,
#'   index_data_file = "/33KG/33kg_index.gz",
#'   reference_data_file = "/33KG/33kg_geno.gz",
#'   ref_out_file = "33kg_chr14_region_geno.txt"
#' )
#' }
#' @export
extract_reg_data <- function(chr_num, start_bp, end_bp, num_pops, index_data_file, reference_data_file, ref_out_file) {
    invisible(.Call(`_refPanelTools_extract_reg_data`, chr_num, start_bp, end_bp, num_pops, index_data_file, reference_data_file, ref_out_file))
}

#' Test Whether a BGZF File Can Be Opened
#'
#' Opens the specified BGZF-compressed file, reads the first line, prints it
#' to the console, and closes the file. Use this to verify that a reference
#' panel file is readable before running longer extraction jobs.
#'
#' @param gz_file Character. Path to the BGZF-compressed file to test.
#'
#' @return Invisibly returns \code{NULL}. Prints the first line of the file
#'   to the console.
#'
#' @examples
#' \dontrun{
#' test_gz_file("/33KG/33kg_geno.gz")
#' }
#' @export
test_gz_file <- function(gz_file) {
    invisible(.Call(`_refPanelTools_test_gz_file`, gz_file))
}

#' @name get_geno_info
#' @keywords internal
get_geno_info <- function(fpos, reference_data_file) {
    .Call(`_refPanelTools_get_geno_info`, fpos, reference_data_file)
}

#' @name largeval
#' @keywords internal
largeval <- function(val) {
    .Call(`_refPanelTools_largeval`, val)
}

#' @name simulate_zscore
#' @keywords internal
simulate_zscore <- function() {
    invisible(.Call(`_refPanelTools_simulate_zscore`))
}

