# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Record the Byte Offset of Every Line in a BGZF File
#'
#' Walks a BGZF-compressed genotype file and writes, for each line, the virtual
#' file offset at which it starts and its length. This is the offset
#' \code{bgzf_seek()} consumes, encoding the compressed position of the line's
#' block and its position within that block.
#'
#' This is a building block, not a finished index. The functions that read a
#' reference panel -- \code{\link{extract_chr_data}},
#' \code{\link{extract_reg_data}}, \code{\link{simulate_af1_z}} and the rest --
#' take a seven-column index (\code{rsid chr bp a1 a2 af1ref fpos}), and
#' \code{indexer} supplies only its last column. Its purpose is to recompute
#' offsets after a new genotype file has been derived from an existing panel:
#' the offsets in the original index no longer apply to the new file, so the
#' \code{fpos} column has to be replaced while the SNP metadata is carried over
#' unchanged. See the example.
#'
#' @param reference_data_file Character. Path to the BGZF-compressed genotype
#'   file to scan (e.g. \code{"/33KG/33kg_geno.gz"}).
#' @param output_file Character. Path for the output. One line per input line,
#'   containing \code{fpos line_length}, in file order.
#'
#' @return Invisibly returns \code{NULL}. Writes the offsets to
#'   \code{output_file}.
#'
#' @section Writing the offsets back out:
#' Offsets into a whole-genome panel are far larger than R's integer range.
#' Read them with something that preserves them exactly -- \code{fread()}
#' returns an \code{integer64} column when \pkg{bit64} is installed -- and
#' check that the written index has not picked up scientific notation. A
#' \code{fpos} written as \code{1.2e+15} parses as \code{1}, which seeks a few
#' bytes into the file rather than to the intended SNP.
#'
#' @seealso \code{\link{extract_chr_data}} for producing the per-chromosome
#'   genotype file that this function then indexes.
#'
#' @examples
#' \dontrun{
#' # Split a whole-genome panel into per-chromosome panels. The genotype
#' # records are unchanged, but their positions in the new file are not, so
#' # the fpos column of the index has to be rebuilt.
#' library(data.table)
#'
#' ref_index <- fread("/33KG/33kg_index.gz")   # rsid chr bp a1 a2 af1ref fpos
#'
#' for (chr_num in 1:22) {
#'   geno_out <- sprintf("/33KG/chr_data/33kg_chr%d_geno", chr_num)
#'   extract_chr_data(chr_num, 29, "/33KG/33kg_index.gz", "/33KG/33kg_geno.gz",
#'                    geno_out)
#'   stopifnot(system(paste("bgzip -f", geno_out)) == 0L)
#'
#'   offsets_file <- tempfile()
#'   indexer(paste0(geno_out, ".gz"), offsets_file)
#'   offsets <- fread(offsets_file)             # fpos line_length
#'
#'   # extract_chr_data() writes SNPs in index order, and indexer() reads them
#'   # back in file order, so the two line up row for row.
#'   chr_index <- ref_index[ref_index$V2 == chr_num, ]
#'   stopifnot(nrow(chr_index) == nrow(offsets))
#'   chr_index$V7 <- offsets$V1                 # replace fpos
#'
#'   index_out <- sprintf("/33KG/chr_data/33kg_chr%d_index", chr_num)
#'   fwrite(chr_index, index_out, quote = FALSE, sep = " ",
#'          row.names = FALSE, col.names = FALSE)
#'   stopifnot(system(paste("bgzip -f", index_out)) == 0L)
#' }
#' }
#' @export
indexer <- function(reference_data_file, output_file) {
    invisible(.Call(`_refPanelTools_indexer`, reference_data_file, output_file))
}

#' Compute Overall Reference Allele Frequency (AF1) per SNP
#'
#' Reads the BGZF-compressed reference genotype file and computes the
#' alternate allele frequency (AF1) across all populations combined.
#' AF1 is rounded to 5 decimal places.
#'
#' @param reference_data_file Character. Path to the BGZF-compressed reference
#'   genotype file.
#' @param num_pops Integer. Total number of populations in the reference panel
#'   (e.g. \code{29} for 33KG).
#' @param output_file Character. Path for the output file. Each line contains
#'   the AF1 value for the corresponding SNP.
#'
#' @return Invisibly returns \code{NULL}. Writes one AF1 value per line to
#'   \code{output_file}, rounded to 5 decimal places.
#'
#' @examples
#' \dontrun{
#' cal_af1ref(
#'   reference_data_file = "/33KG/33kg_geno.gz",
#'   num_pops = 29,
#'   output_file = "33kg_af1ref.txt"
#' )
#' }
#' @export
cal_af1ref <- function(reference_data_file, num_pops, output_file) {
    invisible(.Call(`_refPanelTools_cal_af1ref`, reference_data_file, num_pops, output_file))
}

#' Extract Genotype Data for a Single Chromosome
#'
#' Extracts all SNP genotype records for a specified chromosome from the
#' BGZF-compressed reference panel, using the index file to seek efficiently.
#'
#' @param chr_num Integer. Chromosome number (1--22).
#' @param num_pops Integer. Total number of populations in the reference panel.
#' @param index_data_file Character. Path to the BGZF-compressed reference
#'   panel index file, whose columns are
#'   \code{rsid chr bp a1 a2 af1ref fpos}. This is not the two-column output of
#'   \code{\link{indexer}}, which supplies only the \code{fpos} column.
#' @param reference_data_file Character. Path to the BGZF-compressed reference
#'   genotype file.
#' @param ref_out_file Character. Output file path. Each line is a raw genotype
#'   record for one SNP.
#'
#' @return Invisibly returns \code{NULL}. Writes genotype records to
#'   \code{ref_out_file}.
#'
#' @examples
#' \dontrun{
#' extract_chr_data(
#'   chr_num = 22,
#'   num_pops = 29,
#'   index_data_file = "/33KG/33kg_index.gz",
#'   reference_data_file = "/33KG/33kg_geno.gz",
#'   ref_out_file = "33kg_chr22_geno.txt"
#' )
#' }
#' @export
extract_chr_data <- function(chr_num, num_pops, index_data_file, reference_data_file, ref_out_file) {
    invisible(.Call(`_refPanelTools_extract_chr_data`, chr_num, num_pops, index_data_file, reference_data_file, ref_out_file))
}

#' Extract Genotype Data for Specific Populations on One Chromosome
#'
#' Extracts SNP genotype data for a user-specified subset of populations
#' on a single chromosome. Population names are matched case-insensitively
#' against the reference population description file.
#'
#' @param chr_num Integer. Chromosome number (1--22).
#' @param pop_vec Character vector. Population abbreviations to include
#'   (e.g. \code{c("CEU", "YRI")}). Case-insensitive.
#' @param index_data_file Character. Path to the BGZF-compressed reference
#'   panel index file, whose columns are
#'   \code{rsid chr bp a1 a2 af1ref fpos}.
#' @param reference_data_file Character. Path to the BGZF-compressed reference
#'   genotype file.
#' @param reference_pop_desc_file Character. Path to the population description
#'   file (columns: \code{pop_abb num_subj sup_pop_abb}, with a header row).
#' @param ref_out_file Character. Output file path. Each line contains genotype
#'   strings and AF1 values for the selected populations only.
#'
#' @return Invisibly returns \code{NULL}. Writes filtered genotype records to
#'   \code{ref_out_file}.
#'
#' @examples
#' \dontrun{
#' extract_chr_pop_data(
#'   chr_num = 22,
#'   pop_vec = c("CEU", "YRI"),
#'   index_data_file = "/33KG/33kg_index.gz",
#'   reference_data_file = "/33KG/33kg_geno.gz",
#'   reference_pop_desc_file = "/33KG/33kg_pop_desc.txt",
#'   ref_out_file = "33kg_chr22_CEU_YRI_geno.txt"
#' )
#' }
#' @export
extract_chr_pop_data <- function(chr_num, pop_vec, index_data_file, reference_data_file, reference_pop_desc_file, ref_out_file) {
    invisible(.Call(`_refPanelTools_extract_chr_pop_data`, chr_num, pop_vec, index_data_file, reference_data_file, reference_pop_desc_file, ref_out_file))
}

#' Extract Population-Level AF1 for All SNPs on One Chromosome
#'
#' For each SNP on the specified chromosome, reads the per-population allele
#' frequency (AF1) fields from the reference genotype file and writes them
#' to the output — one line per SNP, space-separated AF1 values in the order
#' populations appear in the population description file.
#'
#' @param chr_num Integer. Chromosome number (1--22).
#' @param index_data_file Character. Path to the BGZF-compressed reference
#'   panel index file, whose columns are
#'   \code{rsid chr bp a1 a2 af1ref fpos}.
#' @param reference_data_file Character. Path to the BGZF-compressed reference
#'   genotype file.
#' @param reference_pop_desc_file Character. Path to the population description
#'   file (columns: \code{pop_abb num_subj sup_pop_abb}, with a header row).
#' @param ref_out_file Character. Output file path. Each line contains
#'   space-separated AF1 values for all populations for one SNP.
#'
#' @return Invisibly returns \code{NULL}. Writes AF1 matrix rows to
#'   \code{ref_out_file}.
#'
#' @examples
#' \dontrun{
#' extract_all_af1(
#'   chr_num = 22,
#'   index_data_file = "/33KG/33kg_index.gz",
#'   reference_data_file = "/33KG/33kg_geno.gz",
#'   reference_pop_desc_file = "/33KG/33kg_pop_desc.txt",
#'   ref_out_file = "33kg_chr22_af1.txt"
#' )
#' }
#' @export
extract_all_af1 <- function(chr_num, index_data_file, reference_data_file, reference_pop_desc_file, ref_out_file) {
    invisible(.Call(`_refPanelTools_extract_all_af1`, chr_num, index_data_file, reference_data_file, reference_pop_desc_file, ref_out_file))
}

#' Simulate AF1 and Association Z-scores Across All Chromosomes
#'
#' For each SNP across all chromosomes, draws a bootstrap sample of subjects
#' from specified populations (sampling with replacement), simulates a null
#' phenotype (standard normal), and computes the OLS association Z-score.
#' Use this to generate genome-wide null Z-score distributions.
#'
#' Sampling uses R's random number generator, so a run is reproducible by
#' calling [set.seed()] beforehand.
#'
#' @param pop_vec Character vector. Population abbreviations to sample from
#'   (e.g. `c("CEU", "YRI")`). Case-insensitive. Each population may appear
#'   at most once.
#' @param num_sim_vec Integer vector. Number of subjects to sample from each
#'   population, where `num_sim_vec[i]` is the sample size for `pop_vec[i]`.
#'   Must be the same length as `pop_vec` and contain positive values. The
#'   pairing is positional, so `pop_vec` may be given in any order; it need
#'   not follow the order of the population description file.
#' @param index_data_file Character. Path to the BGZF-compressed reference
#'   panel index file, whose columns are
#'   \code{rsid chr bp a1 a2 af1ref fpos}.
#' @param reference_data_file Character. Path to the BGZF-compressed reference
#'   genotype file.
#' @param reference_pop_desc_file Character. Path to the population description
#'   file.
#' @param ref_out_file Character. Output file path. Space-separated columns:
#'   `rsid chr bp a1 a2 sim_af1 sim_z`. `sim_z` is `NA` for SNPs that are
#'   monomorphic in the bootstrap sample, where the slope and its standard
#'   error are undefined. Values are rounded to 5 decimal places.
#'
#' @return Invisibly returns `NULL`. Writes simulation results to
#'   `ref_out_file`.
#'
#' @seealso [simulate_af1_z()] for single-chromosome simulation.
#'
#' @examples
#' \dontrun{
#' set.seed(1)
#' simulate_af1_z_allchr(
#'   pop_vec = c("CEU", "YRI"),
#'   num_sim_vec = c(100, 100),
#'   index_data_file = "/33KG/33kg_index.gz",
#'   reference_data_file = "/33KG/33kg_geno.gz",
#'   reference_pop_desc_file = "/33KG/33kg_pop_desc.txt",
#'   ref_out_file = "sim_allchr_results.txt"
#' )
#' }
#' @export
simulate_af1_z_allchr <- function(pop_vec, num_sim_vec, index_data_file, reference_data_file, reference_pop_desc_file, ref_out_file) {
    invisible(.Call(`_refPanelTools_simulate_af1_z_allchr`, pop_vec, num_sim_vec, index_data_file, reference_data_file, reference_pop_desc_file, ref_out_file))
}

#' Simulate AF1 and Association Z-scores for One Chromosome
#'
#' Same simulation procedure as [simulate_af1_z_allchr()] but restricted to a
#' single chromosome. Bootstrap subject indices are drawn once and reused
#' across all SNPs on that chromosome (consistent sampling).
#'
#' Sampling uses R's random number generator, so a run is reproducible by
#' calling [set.seed()] beforehand.
#'
#' @param chr_num Integer. Chromosome number (1--22).
#' @param pop_vec Character vector. Population abbreviations to sample from.
#'   Case-insensitive. Each population may appear at most once.
#' @param num_sim_vec Integer vector. Number of subjects to sample per
#'   population, where `num_sim_vec[i]` is the sample size for `pop_vec[i]`.
#'   Must be the same length as `pop_vec` and contain positive values. The
#'   pairing is positional, so `pop_vec` may be given in any order; it need
#'   not follow the order of the population description file.
#' @param index_data_file Character. Path to the BGZF-compressed reference
#'   panel index file, whose columns are
#'   \code{rsid chr bp a1 a2 af1ref fpos}.
#' @param reference_data_file Character. Path to the BGZF-compressed reference
#'   genotype file.
#' @param reference_pop_desc_file Character. Path to the population description
#'   file.
#' @param ref_out_file Character. Output file path. Space-separated columns:
#'   `rsid chr bp a1 a2 sim_af1 sim_z`. `sim_z` is `NA` for SNPs that are
#'   monomorphic in the bootstrap sample, where the slope and its standard
#'   error are undefined. Values are rounded to 5 decimal places.
#'
#' @return Invisibly returns `NULL`. Writes simulation results to
#'   `ref_out_file`.
#'
#' @seealso [simulate_af1_z_allchr()] for genome-wide simulation.
#'
#' @examples
#' \dontrun{
#' set.seed(1)
#' simulate_af1_z(
#'   chr_num = 22,
#'   pop_vec = c("CEU", "YRI"),
#'   num_sim_vec = c(100, 100),
#'   index_data_file = "/33KG/33kg_index.gz",
#'   reference_data_file = "/33KG/33kg_geno.gz",
#'   reference_pop_desc_file = "/33KG/33kg_pop_desc.txt",
#'   ref_out_file = "sim_chr22_results.txt"
#' )
#' }
#' @export
simulate_af1_z <- function(chr_num, pop_vec, num_sim_vec, index_data_file, reference_data_file, reference_pop_desc_file, ref_out_file) {
    invisible(.Call(`_refPanelTools_simulate_af1_z`, chr_num, pop_vec, num_sim_vec, index_data_file, reference_data_file, reference_pop_desc_file, ref_out_file))
}

#' Extract Genotype Data for a Genomic Region
#'
#' Extracts all SNP genotype records within a specified base-pair range
#' on a chromosome. Uses the index file for efficient random access into
#' the BGZF-compressed reference panel.
#'
#' @param chr_num Integer. Chromosome number (1--22).
#' @param start_bp Integer. Start base pair position (inclusive).
#' @param end_bp Integer. End base pair position (inclusive).
#' @param num_pops Integer. Total number of populations in the reference panel.
#' @param index_data_file Character. Path to the BGZF-compressed reference
#'   panel index file, whose columns are
#'   \code{rsid chr bp a1 a2 af1ref fpos}.
#' @param reference_data_file Character. Path to the BGZF-compressed reference
#'   genotype file.
#' @param ref_out_file Character. Output file path. Each line is a raw genotype
#'   record for one SNP in the region.
#'
#' @return Invisibly returns \code{NULL}. Writes genotype records to
#'   \code{ref_out_file}.
#'
#' @examples
#' \dontrun{
#' extract_reg_data(
#'   chr_num = 14,
#'   start_bp = 104000000,
#'   end_bp = 104200000,
#'   num_pops = 29,
#'   index_data_file = "/33KG/33kg_index.gz",
#'   reference_data_file = "/33KG/33kg_geno.gz",
#'   ref_out_file = "33kg_chr14_region_geno.txt"
#' )
#' }
#' @export
extract_reg_data <- function(chr_num, start_bp, end_bp, num_pops, index_data_file, reference_data_file, ref_out_file) {
    invisible(.Call(`_refPanelTools_extract_reg_data`, chr_num, start_bp, end_bp, num_pops, index_data_file, reference_data_file, ref_out_file))
}

#' Read a Genomic Region into R
#'
#' Backs \code{\link{read_region}}. Returns the SNP metadata and the genotype
#' records for a region together, in one pass over the index.
#'
#' \code{\link{extract_reg_data}} discards the metadata it has already parsed
#' and writes only the genotype records, which leaves the caller re-reading the
#' whole index in R to recover it. Here the fields are kept as they are parsed,
#' so the cost is proportional to the region rather than to the index.
#'
#' @param chr_num Integer. Chromosome number.
#' @param start_bp,end_bp Integer. Inclusive base pair range.
#' @param num_pops Integer. Number of populations in the panel. Each genotype
#'   record must hold exactly \code{2 * num_pops} fields.
#' @param index_data_file,reference_data_file Character. Paths to the
#'   BGZF-compressed index and genotype files.
#'
#' @return A list with \code{rsid}, \code{chr}, \code{bp}, \code{a1},
#'   \code{a2}, \code{af1ref} (\code{bp} as an integer), a character matrix
#'   \code{geno} and a numeric
#'   matrix \code{af1}, both with one row per SNP and one column per
#'   population. Zero-length for a region holding no SNPs.
#'
#' @name read_reg_records
#' @keywords internal
read_reg_records <- function(chr_num, start_bp, end_bp, num_pops, index_data_file, reference_data_file) {
    .Call(`_refPanelTools_read_reg_records`, chr_num, start_bp, end_bp, num_pops, index_data_file, reference_data_file)
}

#' Test Whether a BGZF File Can Be Opened
#'
#' Opens the specified BGZF-compressed file, reads the first line, prints it
#' to the console, and closes the file. Use this to verify that a reference
#' panel file is readable before running longer extraction jobs.
#'
#' @param gz_file Character. Path to the BGZF-compressed file to test.
#'
#' @return Invisibly returns \code{NULL}. Prints the first line of the file
#'   to the console.
#'
#' @examples
#' \dontrun{
#' test_gz_file("/33KG/33kg_geno.gz")
#' }
#' @export
test_gz_file <- function(gz_file) {
    invisible(.Call(`_refPanelTools_test_gz_file`, gz_file))
}

#' @name get_geno_info
#' @keywords internal
get_geno_info <- function(fpos, reference_data_file) {
    .Call(`_refPanelTools_get_geno_info`, fpos, reference_data_file)
}

#' @name largeval
#' @keywords internal
largeval <- function(val) {
    .Call(`_refPanelTools_largeval`, val)
}

#' @name simulate_zscore
#' @keywords internal
simulate_zscore <- function() {
    invisible(.Call(`_refPanelTools_simulate_zscore`))
}

